### ISSUE TITLE
گزارش ایراد

### ISSUE THREAD

**Issue by alircxa** [font-store/font-farboad#1]
درود برشما جناب سوزنچی عزیز
در نظر داشتم گزارش اشکالی رو که بهش برخوردم، در قسمتی که به عنوان "نظرخواهی" ترتیب داده بودید، اعلام کنم؛ اما ظاهراً با مشکل مواجهه اون قسمت (بررسی بفرمایید)... جا داره بابت زحماتی که برای این فونت کشیدید، نهایت سپاسگزاری رو خدمتتون بجا بیارم. ایرادی که بنده بهش برخوردم در تصویر ضمیمه شده مشخص کردم. در مقولۀ علائم نگارشی، در علامت "دو نقطه" / ":" مقداری این کاراکتر بالاتر از خط هست.
ارادتمند.
![untitled](https://cloud.githubusercontent.com/assets/8685650/17514593/b416cc66-5e48-11e6-92fd-4fba5b0833c5.png)

**Comment by zoghal** [comment]
درود بر شما
در هر دو مورد حق با شماست. بزودی نسخه های آخر تمامی فونت ها منتشر میشه. مخصوصا این فونت که تغییرات بسیاری دارد. تا آخر این ماه ۱۰۰٪ ریلیز می‌شوند. 
به دلیل تعداد زیاد فونت‌ها و همچنین برنامه‌ای که در پیش داریم کمی زمان نیاز هست تا طبق برنامه پیش بریم.
ممنون از صبر و حوصله‌تان
شاد و پیروز باشید.
در ضمن حتما اینستای من رو چک کنید تا در جریان آخرین خبر ها قرار بگیرید https://www.instagram.com/saleh.souzanchi/
نمونه متن از تغییرات 

[http://i.share.pho.to/c6dd0936_o.png](http://i.share.pho.to/c6dd0936_o.png)

**Comment by alircxa** [comment]
درود مجدد
در هر صورت بنده به نوبۀ خودم از تمامی زحماتی که برای وب فارسی کشیدین، سپاسگزارم.
بله بله حتما؛ با آیدی زیر دنبال‌تون کردم.
https://www.instagram.com/ar__rn/
ضمناً آقای سوزنچی، یه نکته! از اینکه دیدم شما هم همدان تشریف دارین واقعاً خوشحال شدم! چون اصولاً توی اینجا کمتر کسی پیدا میشه به فکر حمایت از وب فارسی و این چیزا باشه! بنده هم همدان ساکن هستم. خوشحال میشم اگر که هر کمکی از دست بنده ساخته بود در خدمتتون باشم.
با آرزوی موفقیت
ارادتمند.

**Comment by zoghal** [comment]
سپاسگذارم علیرضاخان. 
جدی!!! همدانی؟ ایول بابا بسی خبر خوبی بود. کمی امیدوار شدیم به همدان :)) .
روی چشمم با عث خوشحالی بنده هم میشه. فقط یک ایمیل به من بزنید تا ایمیلتون رو داشته باشم. اینطوری عالی میشه.

**Comment by alircxa** [comment]
منم از آشناییتون جداً خیلی خوشحال شدم. امیدوارم بتونیم همکاری‌های خوبی داشته باشیم. =))
به دیده‌ی چشم. ایمیل هم فرستادم براتون.
ارادتمند.
